import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Agenda RAULT Rémi',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html class="h-full bg-white">
       <body class="h-full" className={inter.className}>{children}</body>
    </html>
  )
}
